# Generated by Django 5.1.7 on 2025-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.CharField(help_text='link to the game', max_length=200),
        ),
    ]
